global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus-cluster' 
    cluster: 'demo-cluster'
    replica: 'prometheus-1'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Scrape Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']